### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 1 in dimension 2 at /tmp/pip-req-build-0vti0ns4/aten/src/THC/generic/THCTensorMath.cu:71

### ISSUE THREAD

**Issue by tangjialiang-jj** [MinfengZhu/DM-GAN#4]
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    algo.train()
  File "/home/tjl/recurrence/DM-GAN-master/code/trainer.py", line 291, in train
    sent_emb, real_labels, fake_labels)
  File "/home/tjl/recurrence/DM-GAN-master/code/miscc/losses.py", line 143, in discriminator_loss
    cond_real_logits = netD.COND_DNET(real_features, conditions)
  File "/home/tjl/anaconda3/envs/t1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tjl/recurrence/DM-GAN-master/code/model.py", line 627, in forward
    h_c_code = torch.cat((h_code, c_code), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 1 in dimension 2 at /tmp/pip-req-build-0vti0ns4/aten/src/THC/generic/THCTensorMath.cu:71
由于我的电脑是2080显卡，所以无法使用pytorch0.4.0，使用pytorch1.2.0后报错，希望作者可以解答一下。

**Comment by MinfengZhu** [comment]
您可以跟踪一下变量的shape，进行一下简单的调试。我本地pytorch0.4.0的环境下测试都是没问题的。我目前无法直接帮您解决这个报错，考虑之后会更新代码支持到1.2.0版本。
